### ISSUE TITLE
高通8gen1+运行问题

### ISSUE THREAD

**Issue by sushuChina** [DakeQQ/YOLO-Depth-Estimation-for-Android#5]
感谢作者的demo，成功在8gen2上跑通了，相较于CPU运行的速度快了15倍。
然后使用同样的步骤在8gen1+的平台上，创建session的时候，老报申请内存出错。
把env的报错等级设置为ORT_LOGGING_LEVEL_VERBOSE后，报错信息如下：
![image](https://github.com/user-attachments/assets/11e72a96-47e8-4312-9782-87f56a31abc3)

**Comment by sushuChina** [comment]
是因为在高通的库环境原因吗

**Comment by DakeQQ** [comment]
谢谢您的支持：）
8_Gen1系列的HTP型号是v69，v7x以前的型号对fp16的计算支持度很低，所以会报错～

**Comment by sushuChina** [comment]
我重新拷贝了我的库文件，我使用您的项目。
* 在app/main/assets文件目录下，所有文件如下：
├── assets
│   ├── camera_fragment_shader.glsl
│   ├── camera_vertex_shader.glsl
│   ├── class.txt
│   ├── Depth_Anything_Metric_V2.ort
│   ├── ld-android.so
│   ├── libbase.so
│   ├── libcdsprpc.so
│   ├── libc++.so
│   ├── libcutils.so
│   ├── libdl_android.so
│   ├── libdmabufheap.so
│   ├── libhardware.so
│   ├── libhidlbase.so
│   ├── libQnnCpu.so
│   ├── libQnnHtpPrepare.so
│   ├── libQnnHtp.so
│   ├── libQnnHtpV69Skel.so
│   ├── libQnnHtpV69.so
│   ├── libQnnHtpV69Stub.so
│   ├── libQnnSystem.so
│   ├── libutils.so
│   ├── libvmmem.so
│   ├── libvndksupport.so
│   ├── Model_TwinLite.ort
│   ├── Model_Yolo_v9c_f16.onnx
│   ├── vendor.qti.hardware.dsp@1.0.so
│   ├── yolo_fragment_shader.glsl
│   └── yolo_vertex_shader.glsl
   * libc++这些库是使用你提供的adb命令，在8gen1的平板上拉下来的。
   * libQnnHtpV69Skel.so、libQnnSystem.so、libQnnHtpV69.so这三个库是在从Qualcomm的Ai库当中qairt/2.26.0.240828/lib/hexagon-v69/unsigned文件夹下拷贝过来。
   * libQnnCpu.so、libQnnHtp.so、libQnnHtpPrepare.so、libQnnHtpV69Stub.so这几个库由于上一行的文件夹之中没有，就从qairt/2.26.0.240828/lib/aarch64-android拷贝过来
   同时我也在您的代码中将V73改成了V69   
![image](https://github.com/user-attachments/assets/984e020d-a8b0-4de2-ba1e-47103a5f665d)
并且为了避免ORT代码里面的soc_arch配置问题，我将一下的配置都注释了。但是还是相同的错误：
![image](https://github.com/user-attachments/assets/c75a0868-a595-41a5-9c65-de81f7dead47)

* 在app/libs/arm64-v8a文件目录下的文件如下：
└── arm64-v8a
    ├── libGLESv3.so
    ├── libomp.so
    ├── libonnxruntime.so
    ├── onnxruntime_c_api.h
    ├── onnxruntime_cxx_api.h
    ├── onnxruntime_cxx_inline.h
    └── onnxruntime_float16.h
    这里面的onnxruntime相关的头文件和onnxruntime都是我重新使用onnxruntime结合Qualcomm的Ai库源码编译得到。这些文件在8_Gen2平台运行正常，换成8gen1就提示内存出错。

**Comment by DakeQQ** [comment]
在close的issue里面曾经有人在8_Gen1成功过，他应该用的是我以前编译的2.24.*版本。 您看看能不能联系上他问问 [cvv-student](https://github.com/cvv-student)

**Comment by sushuChina** [comment]
好的，谢谢。

**Comment by sushuChina** [comment]
谢谢作者，我将这些库都重新拷贝一遍就解决了，可能是因为在libs/arm64-v8a之中的系统不匹配的原因；
另外我想知道请教一个问题，为什么在assets文件夹下放了这些文件并且拷贝到cache，并设置的LD_LIBRARY_PATH和ADSP_LIBRARY_PATH都指向cache文件夹之后，还需要在libs/arm64-v8a放这些库呢？

**Comment by DakeQQ** [comment]
1. ONNXRuntime的源码指出，在编译QNN-HTP Provider时，它会读取位于`/xxx/yyy/libQnnHtp.so`的路径，并将该文件的上级目录`/xxx/yyy`作为搜索其他库文件的基础。然而，对于没有root权限的手机来说，直接访问`/system/lib64`和`/vendor/lib64`是不可行的。因此，需把必要库先复制出来，并且选择一个能够访问的替代路径。我们使用Cache文件夹，但您也可以根据需要选择其他合适的文件夹。

2. 当完成编译并在手机上运行应用程序时，系统首先会在`libs/arm64-v8a`目录下查找所需的库文件。因此，在该目录中也放置一份。您也可以指定另一个具有访问权限的位置，确保Android系统能够找到并加载这些库文件。

总结：由于编译过程和运行时的库文件搜索路径不同，因此需要在两个不同的位置各放置一份，才能满足编译和运行时的需求。

**Comment by sushuChina** [comment]
谢谢，大致明白了，也就是在编译和运行时他们搜索文件的路径不一致导致的。
那也就是说设置的LD_LIBRARY_PATH和ADSP_LIBRARY_PATH都是在编译时起作用，而程序运行的时候实际上默认搜索路径不是通过这两个属性设置的。

**Comment by DakeQQ** [comment]
Hello~建议您再拉一份最新的代码，这两天大幅改善了GPU图像预处理 ，YOLO检测体验更好了：）

**Comment by sushuChina** [comment]
好的，我尝试一下您的新代码

**Comment by sushuChina** [comment]
您好，请问您尝试过使用具有动态输入形状的model使用QNN加速的尝试了。我参照您的demo加载了一个降噪的模型，当加载模型时如果是动态输入形状时，就无法加速，如果是固定输入形状就能正常加速。

**Comment by DakeQQ** [comment]
QNN-HTP不支持动态尺寸的输入和输出。用Netron打开，只要尺寸维度不是纯数字的节点都应该会编译失败退回ORT-CPU provider, 可以打开verbose, 然后Locat的过滤关键字填`package:mine number`，就能看到有多少node分配给各provider.

(问一句。。您是怎么在Android上成功跑动态尺寸ORT-CPU模型的？！ 我添加dynamic_axes导出的模型都没正常输出过。。。)

**Comment by sushuChina** [comment]
在Android的CPU上跑onnxruntime的模型，就是在torch.onnx.export导出的时候添加dynamic_axes属性。如下图
![image](https://github.com/user-attachments/assets/16d11090-a021-499a-aeb9-482114ea4d29)
在这里面，dynamic_axes里面添加了的轴它就会设定为动态，没添加的轴就会和你的输入图片（图中的`img_L`）一致。

**Comment by sushuChina** [comment]
我用的模型是https://github.com/cszn/KAIR里面的fdncnn，你可以尝试一下

**Comment by sushuChina** [comment]
我用的模型是https://github.com/cszn/KAIR 里面的fdncnn，你可以尝试一下

**Comment by DakeQQ** [comment]
那Android里的ORT加载和推理的C++代码需要针对动态尺寸修改吗？

**Comment by sushuChina** [comment]
不需要的，我是直接加载和推理的。

**Comment by zylo117** [comment]
实测2.31 QNN支持动态IO尺寸的

![Image](https://github.com/user-attachments/assets/f687b3af-5bb5-4fca-add9-14dbcd109157)

**Comment by sushuChina** [comment]
好的，我尝试一下。我之前用的2.27不支持动态输入，为了使用准备了几个不同大小输入的模型，搞得资源包好大。现在可以瘦身了

**Comment by DakeQQ** [comment]
开发文档有提到部份算子在C轴和W轴上 (NHWC)，且数据类型为uint16时 (在SDK release note 备注不是INT16)，允许动态尺寸。例如常用的[MatMul](https://docs.qualcomm.com/bundle/publicresource/topics/80-63442-50/HtpOpDefSupplement.html#matmul)

![Image](https://github.com/user-attachments/assets/e9c233b2-86e4-4cdb-b095-f17c0a7a270d)
