### ISSUE TITLE
Yolo models on Qualcomm X Elite Dev Box

### ISSUE THREAD

**Issue by fobrs** [DakeQQ/YOLO-Depth-Estimation-for-Android#6]
Hi, I use your quantized YOLO model **Model_Yolo_v9c_f16.onnx** downloaded from googledrive to get Yolo running on the Qualcomm X Elite Hexagon NPU with DirectML. You state that these are v9 but Netron shows they are v10. At least I need to use function **detectYOLOv10()** from [here](https://github.com/ShahriarRezghi/objdetex/blob/main/src/objdetex/objdetex.cpp) to get the bboxes and classifications from the output tensor.

Can you explain?

**Comment by DakeQQ** [comment]
I'm sorry for the confusion, but it does show version v9c at `METADATA-description`. Additionally, we have optimized the original v9 code (in the folder: modeling_modified/tasks.py, lines 148-172), changing the output of the v9 model to` [x, y, w, h, max_score, max_indices]`. This output format is indeed similar to the results of version v10.
<img width="744" alt="截屏2024-11-04 18 27 50" src="https://github.com/user-attachments/assets/7c8d5f40-27cc-4a22-80ee-abe9288f87c3">

**Comment by fobrs** [comment]
Hi, it works now. I'm using one of your models over here:
https://github.com/fobrs/yolov9_npu
